name: Sync upstream

on:
  schedule:
    - cron: "0 3 */14 * *"
  workflow_dispatch:
    inputs:
      target_commit:
        description: 'Commit hash (leave blank to use latest commit)'
        required: false
        type: string

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4
        with:
          ref: main 
          persist-credentials: false
          # 【新增】必须设置为 0，获取所有历史提交记录，供比对使用
          fetch-depth: 0 

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: shuaiplus/nodewarden
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.PAT_TOKEN }}
          # 【修改这里】添加 -X ours 参数，意思是发生冲突时以我们(本地)的修改为准
          upstream_pull_args: '-X ours'
